#!/usr/bin/env bash
# This script displays the following content of the file /etc/passwd:
# username
# user id
# Home directory path for the user

exec < /etc/passwd

while read -r passwd
      do
	echo "$passwd" | cut -d ":" -f1,3,6
done
